//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVu
    {
        public int MaDichVu { get; set; }
        public string TieuDeDichVu { get; set; }
        public string NoiDungDichVu { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public Nullable<bool> DaXoa { get; set; }
        public Nullable<int> MaLoaiDV { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual LoaiDichVu LoaiDichVu { get; set; }
    }
}
