//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioiThieu
    {
        public int MaGioiThieu { get; set; }
        public string TieuDeGT { get; set; }
        public string NoiDungGT { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public Nullable<bool> DaXoa { get; set; }
        public Nullable<int> MaLoaiGT { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual LoaiGioiThieu LoaiGioiThieu { get; set; }
    }
}
