//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MGG
    {
        public int idmgg { get; set; }
        public string MaGG { get; set; }
        public string LoaiGiam { get; set; }
        public Nullable<double> trigia { get; set; }
        public Nullable<System.DateTime> thoihan { get; set; }
    }
}
