//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuyenDung
    {
        public int MaTuyenDung { get; set; }
        public string TieuDeTuyenDung { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public string NoiDungTuyenDung { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public Nullable<bool> DaXoa { get; set; }
        public string HinhAnh { get; set; }
    }
}
